network:
  name: redundanet
  version: 2.0.0
  domain: redundanet.local
  vpn_network: 10.100.0.0/16
  tahoe:
    shares_needed: 3
    shares_happy: 7
    shares_total: 10
    reserved_space: 1G
introducer_furl: null
nodes:
- name: node-dd2be971
  internal_ip: 10.100.0.10
  vpn_ip: 10.100.0.10
  gpg_key_id: 333BEC68DD2BE971
  region: europe
  status: pending
  roles:
  - tinc_vpn
  - tahoe_storage
  ports:
    tinc: 655
    tahoe_storage: 3457
    tahoe_client: 3456
    tahoe_introducer: 3458
  storage_contribution: 100GB
  is_publicly_accessible: false
- name: node-78726a62
  internal_ip: 10.100.0.11
  vpn_ip: 10.100.0.11
  gpg_key_id: D8FF14FC78726A62
  region: europe
  status: pending
  roles:
  - tinc_vpn
  - tahoe_storage
  ports:
    tinc: 655
    tahoe_storage: 3457
    tahoe_client: 3456
    tahoe_introducer: 3458
  storage_contribution: 10GB
  is_publicly_accessible: true
  public_ip: 168.119.173.11
